### PR TITLE
Vertical architecture slice

### LINKED ISSUE #28: Prototype registration and login flow
* [ ] Create account
  * [ ] email
  * [ ] password
  * [ ] validate email does not exit
  * [ ] hash password
  * [ ] email verification (?)
* [ ] Log in
* [ ] Blank "main pipeline" skeleton to redirect to on successful login

### PR DESCRIPTION
**Pull request by blackjackkent**
DEPENDS ON #37 
RESOLVES #28

### CODE REVIEW

**Comment by 0xazure** [comment]
Finally had a chance to take a look at this, running into a couple issues currently:

- `undefined method 'set_session' for #<UsersController:0x007f6265867a30>` after attempting to register a new account
- `The action 'index' could not be found for UsersController` when attempting to visit `/users`

@blackjackkent could you clarify what functionality you're looking to implement in this PR so we know what's clear for testing and what's still in progress?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cecce5d2bd8c1f91f988bf1d245d8efaeb1189b1
  * Your subject line is longer than 50 characters

Guidelines are available at https://github.com/new-xkit/pipeline/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by blackjackkent** [comment]
@0xazure Updated. I'm...not entirely sure how that happened; I think I renamed my `init_session` function and forgot to rename the places where it was called and I deserve the cone of shame for this.

Per my comment in Gitter a while back this is basically just the login/signup flow. Going to the site root will give you the login page with a signup link; from there you can signup a new account and then log out and log in. (The users controller doesn't have an index method anymore.)

The tests don't pass at the moment; I'd forgotten about that also. :P I still need to figure out how to unit test the custom error messages I set up for user validation.

**Comment by 0xazure** [comment]
Here's my UI/UX first impressions, more in-depth code review coming soon.

#### General

- Everything looks really wide
  - Buttons can probably be shrunk horizontally
- Should probably default to the registration page, like [GitHub](https://github.com) and [Tumblr](https://tumblr.com) do

#### /login

- Give the whole form some left/right padding
- Missing 'Don't have an account?' / 'Already have an account' cross-linking between login & registration pages

#### /users/new
- Why not `/register`?
- Get rid of password confirmation
  - See [this article](http://uxmovement.com/forms/why-the-confirm-password-field-must-die/) for some UX perspective
  - [Some more examples](http://www.leemunroe.com/confirm-passwords-signup/) of sites with and without password confirmation
- Form feels a bit unbalanced, even without the password confirmation field
  - Form field-heavy on the left side, and text-heavy on the right
  - Any other (optional) information we want to ask when they create an alias?
- Mixed terminology may be confusing
  - Is it a username or an alias?
  - Do we want to leverage a "brand" term, like how Tumblr calls them "blogs"?  "Create your first spout/tap/spigot"?

**Comment by blackjackkent** [comment]
Closing because my old fork disappeared when we transferred the repo. Continued at #41

**Pull request closed without merging**
